### ISSUE TITLE
upgrade cloud_firestore to 3.1.0

### ISSUE THREAD

**Issue by alexodus** [vedartm/paginate_firestore#105]
Please, upgrade cloud_firestore from 2.5.3 to 3.1.0

**Comment by Freyien** [comment]
> Please, upgrade cloud_firestore from 2.5.3 to 3.1.0

You can use dependency overrides for rewrite cloud_firestore version

`
dependencias:
  ...
dependency_overrides:
  cloud_firestore: ^3.1.0`

**Comment by vedartm** [comment]
Version 1.0.3 has the latest version of all the packages 🎉
