### ISSUE TITLE
Upgrade dependencies

### ISSUE THREAD

**Issue by kkorgol** [vedartm/paginate_firestore#111]
Please upgrade dependencies to latest versions

> Because paginate_firestore 1.0.3 depends on flutter_bloc ^7.3.3 and no versions of paginate_firestore match >1.0.3 <2.0.0, paginate_firestore ^1.0.3 requires flutter_bloc ^7.3.3.
> So, because app depends on both paginate_firestore ^1.0.3 and flutter_bloc ^8.0.0, version solving failed.

**Comment by kkorgol** [comment]
Nope, to solve this issue, version of flutter_bloc should be updated to latest in paginate_firestore package dependencies by author/contributors

**Comment by vedartm** [comment]
@kkorgol thanks for using the package. I have updated the dependencies in the latest version v1.0.3+1 🎉
