### ISSUE TITLE
Dependency issue with flutter_bloc

### ISSUE THREAD

**Issue by sauravgpt** [vedartm/paginate_firestore#114]
paginate_firestore: ^1.0.3 depends on flutter_bloc ^7.3.3 and I'm using  ^8.0.1 flutter_bloc, this causing confliction please resolve this issue. 

Thank you in advance!

**Comment by vedartm** [comment]
@sauravgpt thanks for using the package. I have updated the dependencies in the latest version v1.0.3+1 🎉
