### ISSUE TITLE
An error occurred while parsing query arguments, this is most likely an error with this SDK

### ISSUE THREAD

**Issue by officialFlutterDeveloper** [vedartm/paginate_firestore#117]
fireStoreGlobal
                    .collection('TestUsers')
                    .orderBy('BoostDate', descending: true)
                    .orderBy('Points', descending: true)
                    .where('ID',
                        whereNotIn: ['57234810-83fc-11ec-bd0d-ab1eb222bb76'])
                    .where('Gender', isEqualTo: 'Gender Fluid')
                    .where('City', isEqualTo: city)
                    .where('DOB',
                        isLessThanOrEqualTo: minAgeToQueryWith,
                        isGreaterThan: maxAgeToQueryWith),
                        
                        
                        
                        
when I run this query my app crashes with following error

An error occurred while parsing query arguments, this is most likely an error with this SDK. (
	0   CoreFoundation                      0x000000011a003fba __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x0000000119eadff5 objc_exception_throw + 48
	2   FirebaseFirestore                   0x000000010f7dd08b _ZN8firebase9firestore4util16ObjcThrowHandlerENS1_13ExceptionTypeEPKcS4_iRKNSt3__112basic_stringIcNS5_11char_traitsIcEENS5_9allocatorIcEEEE + 683
	3   FirebaseFirestore                   0x000000010f7dc3c5 _ZN8firebase9firestore4util5ThrowENS1_13ExceptionTypeEPKcS4_iRKNSt3__112basic_stringIcNS5_11char_traitsIcEENS5_9allocatorIcEEEE + 53
	4   FirebaseFirestore                   0x000000010fa9f865 _ZN8firebase9firestore4util20ThrowInvalidArgumentIJNSt3__112basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEES9_S9_EEEvPKcDpRKT_ + 85
	5   FirebaseFirestore                   0x000000010fa9f4a7 _ZNK8firebase9firestore3api5Query20ValidateOrderByFieldERKNS0_5model9FieldPathES6_ + 119
	6   FirebaseFirestore                   0x000000010fa9ef46 _ZNK8firebase9firestore3api5Que
Lost connection to device.

**Comment by vedartm** [comment]
This is out of the scope of the package. Error is from the firestore package. Please post the issue there.
