### ISSUE TITLE
Exception when ScrollController will be disposed

### ISSUE THREAD

**Issue by MoritzOtto** [vedartm/paginate_firestore#122]
Hello, 

As paramter to paginate_firestore we provide a scrollcontroller. When using the widget at one time the widget PaginateFirestore will be disposed, while the widget that owns and creats the scrollcontroller is still alive. For that reason I would expect that the provided scrollcontroller wont get disposed. When this happens the seccond time I got the following exception. 

    Exception has occurred. FlutterError (A ScrollController was used after being disposed. 
    Once you have called dispose() on a ScrollController, it can no longer be used.)

Why is the scrollcontroller going to disposed when PaginateFirestore will be disposed? I think for us this will fix our scenario.

regards,
Moritz

**Comment by vedartm** [comment]
Hi @MoritzOtto. Thanks for using the plugin. Since the scroll controller is attached to PaginateFirestore, it gets disposed together. It is the intended behavior as you can see [here](https://github.com/vedartm/paginate_firestore/blob/master/lib/paginate_firestore.dart#L144-L149).
