### ISSUE TITLE
Integration of custom_refresh_indicator

### ISSUE THREAD

**Issue by RoyalCoder88** [vedartm/paginate_firestore#127]
Hi friends,

I really need to use my custom refresh indicator or **custom_refresh_indicator**  for  **paginate_firestore** , how can I achieve this? 
Thanks in advance!

**Comment by vedartm** [comment]
Hi @RoyalCoder88. Thanks for using the package. It is similar to the normal `RefreshIndicator` implementation in the [README.md](https://github.com/vedartm/paginate_firestore/blob/master/README.md). It has the same `onRefresh` attribute.

Feel free to reopen this if you face this issue again.

**Comment by RoyalCoder88** [comment]
Hi @vedartm I tried but didn't manage hot to integrate it properly, can you offer me an example or guide me, please? 
Thanks in advance!
