### ISSUE TITLE
Retrieving a subcolletion

### ISSUE THREAD

**Issue by Miguel-cancino** [vedartm/paginate_firestore#24]
How retrieve a subcollection? The example just show a simple query.

**Comment by claudemircasa** [comment]
I believe it is simple, the firestore documentation shows that you can search for sub-collections in this way (example):

```dart
Firestore.instance.collection('users').doc(Firestore.instance.currentUser.uid).collection('orders').orderBy('id', descending: true);
```

**Comment by Miguel-cancino** [comment]
Thank you. I've already tried, but I need to retrieve all users documents, not just current user´s documents.

**Comment by excogitatr** [comment]
If you are talking about Collection group queries, then the query goes like
```dart
Firestore.instance.collectionGroup('orders').getDocuments()
```
