### ISSUE TITLE
List<DocumentSnapshot> instead of Query

### ISSUE THREAD

**Issue by jenniestrongbow** [vedartm/paginate_firestore#44]
Hi,

Would it be possible for you to add a feature that allows us to use a List of DocumentSnapshot instead of the Query type ?

Thanks

Jennie

**Comment by excogitatr** [comment]
You mean instead of `query` parameter you want to send a list of document snapshot? Could you please explain with example?

**Comment by jenniestrongbow** [comment]
Hi,

Your (fantastic) paginate package has a query attribute that only accepts a Query type. Instead, I'd like to be able to use a List<DocumentSnapshot> type instead.

List<DocumentSnapshot> items = List<DocumentSnapshot>();
PaginateFirestore(
...
query: items,
...)

Thanks!

**Comment by excogitatr** [comment]
Glad you like the package.

Do you mean you will make the query separately and just use the result in the pagination widget?

**Comment by jenniestrongbow** [comment]
Yes, the fact that the package is limited to a Query type is problematic to me as I'd like to use List types. Thanks

**Comment by excogitatr** [comment]
This can be worked on. Please wait for the next version.

**Comment by jenniestrongbow** [comment]
Fantastic!!! Looking forward to testing it. Thanks!

**Comment by onethao** [comment]
any update for this?

**Comment by excogitatr** [comment]
@jenniestrongbow Sorry I forgot to mention. There is a package I made that helps with general pagination which is not tightly coupled with Firestore. Its called `pagination_view` - https://pub.dev/packages/pagination_view. Let me know if this helps.

**Comment by vedartm** [comment]
Hope your issue is resolved. Feel free to reopen this if you face any similar issues.

**Comment by kiloki-official** [comment]
Thanks Vedartm, I LOVE your packages. Thanks a million!
