### ISSUE TITLE
Updating the query of the paginated list

### ISSUE THREAD

**Issue by Aurangseb** [vedartm/paginate_firestore#83]
Hi,

a really useful feature would be the ability to modify the query, e.g. when the user picks a different sort or where condition.

Right now the paginator sticks to the original query  even if you update the query and setState() or use the PaginateRefreshedChangeListener, which makes it impossible to use in more complex scenarios.

**Comment by marc-walton** [comment]
> Hi,
> 
> a really useful feature would be the ability to modify the query, e.g. when the user picks a different sort or where condition.
> 
> Right now the paginator sticks to the original query even if you update the query and setState() or use the PaginateRefreshedChangeListener, which makes it impossible to use in more complex scenarios.

Did you find a way?

**Comment by irshaadMax** [comment]
@marc-walton thanks for the code. It works.
But issue is it will refresh the whole PaginateFirestore widget along with it's header and footer.
Not only the builder it self.
Hope the project owner will fix this issue.

**Comment by Omi231** [comment]
> > Hi,
> > a really useful feature would be the ability to modify the query, e.g. when the user picks a different sort or where condition.
> > Right now the paginator sticks to the original query even if you update the query and setState() or use the PaginateRefreshedChangeListener, which makes it impossible to use in more complex scenarios.
> 
> You can use a key . Something like this
> 
> ```
> PaginateFirestore(
>       key:ValueKey<String>(priceQuery),// priceQuery changes from user interaction
> ```

hello, i am a novice developer. Can u explain it a bit more?

**Comment by marc-walton** [comment]
> > > Hi,
> > > a really useful feature would be the ability to modify the query, e.g. when the user picks a different sort or where condition.
> > > Right now the paginator sticks to the original query even if you update the query and setState() or use the PaginateRefreshedChangeListener, which makes it impossible to use in more complex scenarios.
> > 
> > 
> > You can use a key . Something like this
> > ```
> > PaginateFirestore(
> >       key:ValueKey<String>(priceQuery),// priceQuery changes from user interaction
> > ```
> 
> hello, i am a novice developer. Can u explain it a bit more?

What didn't you understand?

**Comment by Omi231** [comment]
@marc-walton It is giving me error:

`
// defining query
Query q = FirebaseFirestore.instance .collection('subcategories').where('category', isEqualTo: widget.category['ID']).orderBy('ID'); 

changeQuery(){
   setState({
       q = Firebase.instance.collection('items')...; // changing query
  });
}

//in body
PaginateFirebase(
key:  ValueKey<String>(q), // **(q) giving error: The Object type Query<Object> can't be assigned to parameter type String**
query: q,
....
)

// calling changeQuery() somewhere in logic .
`
Can you tell me what I am doing wrong in this code and why is it giving me error?

Thank you for help :)

**Comment by marc-walton** [comment]
> @marc-walton It is giving me error:
> 
> ```
> // defining query
> Query q = FirebaseFirestore.instance .collection('subcategories').where('category', isEqualTo: widget.category['ID']).orderBy('ID'); 
> 
> changeQuery(){
>    setState({
>        q = Firebase.instance.collection('items')...; // changing query
>   });
> }
> 
> //in body
> PaginateFirebase(
> key:  ValueKey<String>(q), // **(q) giving error: 
> 
> Can you tell me what I am doing wrong in this code and why is it giving me error?
> l
> Thank you for help : clears s

> @marc-walton It is giving me error:
> 
> ```
> // defining query
> Query q = FirebaseFirestore.instance .collection('subcategories').where('category', isEqualTo: widget.category['ID']).orderBy('ID'); 
> 
> changeQuery(){
>    setState({
>        q = Firebase.instance.collection('items')...; // changing query
>   });
> }
> 
> //in body
> PaginateFirebase(
> key:  ValueKey<String>(q), // **(q) giving error: The Object type Query<Object> can't be assigned to parameter type String**
> query: q,
> ....
> )
> 
> // calling changeQuery() somewhere in logic .
> ```
> 
> Can you tell me what I am doing wrong in this code and why is it giving me error?
> 
> Thank you for help :)

The error clearly states you can't pass Query<object> , it requires a string.
ValueKey<String>👈.
 So declare a string value say ```String valueForTheKey = "firstQuery"```.

Then pass it in the valueKey<String>(value).
 So whenever the String value is changed , the builders builds again.
The query:q, change it to something like this with if else

```query: valueForTheKey== "firstQuery"? Firebasefirestore......where(value , isEqualTo: 1): valueForTheKey =="secondQuery"? Firebasefirestore......where(value , isEqualTo: 1): q.
Hope I could help you

**Comment by Omi231** [comment]
thank you so much for ur time and help for teaching me a new thing :) u are awesome!

**Comment by vedartm** [comment]
Hope this issue is resolved. Thanks for using the package 🎉. Feel free to reopen if you face this issue.
