### ISSUE TITLE
How does the pagination work?

### ISSUE THREAD

**Issue by abayomiAkanji** [vedartm/paginate_firestore#87]
Hi @vedartm, many thanks for this library.

I would like to make a clarification about the pagination' logic. I couldn't find the info in the pub.dev doc so I thought I could put my question here.
Does the library fetch _new new chuck_ of live data while user scrolls or it fetches _all contents (at once)_ and displays them in batches based on request?

I look forward to your response.

Thanks!

**Comment by vedartm** [comment]
Hi @abayomiAkanji. Glad you liked the package. It fetches a new chunk of live data while the user scrolls.

**Comment by StevAlberts** [comment]
Why does it seem like it fetches everything coz I don't feel any pagination going on? 🤔
