### ISSUE TITLE
Another exception was thrown: The Scrollbar's ScrollController has no ScrollPosition attached.

### ISSUE THREAD

**Issue by waletoyo1** [vedartm/paginate_firestore#89]
Hi, 
I'm getting this error when I use paginate firestore widget inside a TabBarView. 

" Another exception was thrown: The Scrollbar's ScrollController has no ScrollPosition attached."

What could be the problem?

**Comment by vedartm** [comment]
Hi @waletoyo1. Check if this helps.
https://github.com/vedartm/paginate_firestore/issues/91#issuecomment-890576148
