### ISSUE TITLE
Having multiple PaginateFirestore Widgets does not work

### ISSUE THREAD

**Issue by hawkinsjb1** [vedartm/paginate_firestore#92]
It appears as though all PaginateFirestore Widgets default to the first query passed (at least if the initial query results to empty). This is a blocking issue.

I am currently using separating the Paginates by key, query object, and stateful widget

**Comment by hawkinsjb1** [comment]
Nevermind! This was my fault as the key ended up not being unique

**Comment by vedartm** [comment]
Thanks for using the package @hawkinsjb1 🎉
