### ISSUE TITLE
bug in footers/headers

### ISSUE THREAD

**Issue by kiloki-official** [vedartm/paginate_firestore#94]
Hi, I've tried to add widgets to header and footer, but whatever widget I add there ( e.g. a simple Text("ok")) throws 
 "owner._debugCurrentBuildTarget == this , is not true".

Can you please help? 

Thanks

**Comment by kiloki-official** [comment]
I found the solution, SliverToBoxAdapter(). Works perfectly. Thanks

**Comment by kiloki-official** [comment]
Just had to follow your example :-)

**Comment by vedartm** [comment]
Thanks for using the package @kiloki-official. Feel free to reopen this if you face any similar issues.
